{{- if and (.Values.auth.enabled) (not .Values.auth.existingAdminSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "orion.name" . }}
    chart: {{ template "orion.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
  name: {{ template "orion.adminSecret" . }}
        {{ .Release.Name }}-db-secret
type: Opaque
data:
  user: {{ .Values.auth.adminUser | b64enc }}
  password: {{ .Values.auth.adminPassword | b64enc }}
{{- end -}}