REVISION: 8
RELEASED: Tue Oct 23 13:33:12 2018
CHART: orion-0.2.0
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
affinity: {}
container:
  name: orion
  port: 1026
dbHost: mongodb-orion-mongodb-replicaset
dbPassword: mongodb
dbUser: root
extraLabels:
  tier: context-broker
fullnameOverride: ""
image:
  pullPolicy: IfNotPresent
  repository: fiware/orion
  tag: latest
ingress:
  annotations: {}
  enabled: false
  hosts:
  - chart-example.local
  path: /
  tls: []
livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 30
  periodSeconds: 30
  successThreshold: 1
  timeoutSeconds: 5
nameOverride: ""
nodeSelector: {}
readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 30
  successThreshold: 2
  timeoutSeconds: 1
replicaCount: 2
resources: {}
service:
  port: 1026
  type: LoadBalancer
tolerations: []

HOOKS:
MANIFEST:

---
# Source: orion/templates/mongodb-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  #root
  user: cm9vdA==     
  #mongodb
  password: bW9uZ29kYg==
---
# Source: orion/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: orion
  labels:
    app: orion
    chart: orion-0.2.0
    release: orion
    heritage: Tiller
    tier: context-broker
    
spec:
  type: LoadBalancer
  ports:
    - port: 1026
  selector:
    app: orion
    release: orion
---
# Source: orion/templates/orion-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orion 
  labels:
    app: orion 
    chart: orion-0.2.0 
    release: orion 
    heritage: Tiller
    tier: context-broker
    
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orion
      release: orion
      tier: context-broker
      
  template:
    metadata:
      labels:
        app: orion 
        release: orion
        tier: context-broker
        
    spec:
      containers:
        - name: orion
          image: "fiware/orion:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: orion
              containerPort: 1026
              protocol: TCP
          args:                 
            - -dbhost
            - mongodb-orion-mongodb-replicaset
            - -dbuser
            - root
            - -dbpwd
            - mongodb
          livenessProbe:
            exec:
              command:
                - curl
                - http://localhost:1026/version
            initialDelaySeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
            periodSeconds: 30
            successThreshold: 1
          livenessProbe:
            exec:
              command:
                - curl
                - http://localhost:1026/version
            initialDelaySeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
            periodSeconds: 30
            successThreshold: 1
