apiVersion: v1
kind: Service
metadata:
  name: authzforce
  labels: 
    app: authzforce
    tier: idm
spec:
  type: LoadBalancer
  ports:
  - #name: normal
    port: 8080
    targetPort: 8080
  selector:
    app: authzforce
    tier: idm
---

 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: authzforce
   labels:
     app: authzforce
     tier: idm
 spec:
   replicas: 1
   selector:
    matchLabels:
      app: authzforce
      tier: idm
   template:
     metadata:
       labels:
         app: authzforce
         tier: idm
     spec:
       containers:
       - name: authzforce
         image: fiware/authzforce-ce-server:release-8.0.1
         ports:
         - containerPort: 8080
