apiVersion: v1
kind: Service
metadata:
  name: keyrock
  labels: 
    app: keyrock
    tier: idm
spec:
  type: LoadBalancer
  ports:
  - name: idm-normal
    port: 3000
    targetPort: 3000
  - name: idm-ssl
    port: 443
    targetPort: 443
  - name: auth-token-ext
    port: 8000
    targetPort: 8000
  - name: auth-token-int
    port: 5000
    targetPort: 5000    
  - name: azf
    port: 8080
    targetPort: 8080
  selector:
    app: keyrock
    tier: idm
---

 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: keyrock
   labels:
     app: keyrock
     tier: idm
 spec:
   replicas: 1
   selector:
    matchLabels:
      app: keyrock
      tier: idm
   template:
     metadata:
       labels:
         app: keyrock
         tier: idm
     spec:
       containers:
       - name: keyrock
         image: fiware/idm:7.5.1
         ports:
         - containerPort: 3000
         - containerPort: 443
         env:
         - name: IDM_HOST
           value: http://localhost
         - name: IDM_PORT
           value: "3000"
         - name: DATABASE_HOST #default localhost
           value: mysql-rs-write
         - name: IDM_DB_PASS
           value: mysql #default idm
         - name: IDM_DB_NAME 
           value: idm #default idm
         - name: IDM_ADMIN_USER
           value: dodol #default admin
         - name: IDM_ADMIN_EMAIL 
           value: dodol@dodol.com #default admin@test.com
         - name: IDM_ADMIN_PASS
           value: dodol #default 1234
         - name: IDM_AUTHZFORCE_ENABLED
           value: "false" #default false
         - name: IDM_AUTHZFORCE_HOST
           value: idm #default idm - idm/authzforce
         - name: IDM_AUTHZFORCE_PORT
           value: "8080"
         - name: IDM_PDP_LEVEL
           value: basic #basic/advanced
         - name: IDM_SESSION_SECRET
           value: keyrock
         - name: IDM_ENCRYPTION_KEY
           value: idm
         - name: IDM_DEBUG
           value: "true" 
         - name: IDM_HTTPS_ENABLED
           value: "true"
         - name: IDM_HTTPS_PORT
           value: "443"
           

# ENV IDM_HOST "http://localhost"
# ENV IDM_PORT "3000"

# ENV IDM_DEBUG "true"

# ENV IDM_HTTPS_ENABLED true
# ENV IDM_HTTPS_PORT "443"

# ENV IDM_SESSION_SECRET "nodejs_idm"
# ENV IDM_SESSION_DURATION "3600000"

# ENV IDM_OAUTH_AUTH_LIFETIME "300"
# ENV IDM_OAUTH_ACC_LIFETIME "3600"
# ENV IDM_OAUTH_ASK_AUTH true
# ENV IDM_OAUTH_REFR_LIFETIME "1209600"
# ENV IDM_OAUTH_UNIQUE_URL false

# ENV IDM_API_LIFETIME "3600"

# ENV IDM_ENCRYPTION_KEY "nodejs_idm"

# ENV IDM_CORS_ENABLED "false"),
# ENV IDM_CORS_ORIGIN "*"),
# ENV IDM_CORS_METHODS 'GET,HEAD,PUT,PATCH,POST,DELETE'),
# ENV IDM_CORS_ALLOWED_HEADERS undefined
# ENV IDM_CORS_EXPOSED_HEADERS undefined
# ENV IDM_CORS_CREDENTIALS undefined
# ENV IDM_CORS_MAS_AGE undefined
# ENV IDM_CORS_PREFLIGHT false
# ENV IDM_CORS_OPTIONS_STATUS 204

# ENV IDM_PDP_LEVEL "basic"
# ENV IDM_AUTHZFORCE_ENABLED false
# ENV IDM_AUTHZFORCE_HOST "localhost"
# ENV IDM_AUTHZFORCE_PORT" 8080"

# ENV IDM_DB_HOST "localhost"
# ENV IDM_DB_PASS "idm"
# ENV IDM_DB_USER "root"
# ENV IDM_DB_NAME "idm"
# ENV IDM_DB_DIALECT "mysql"
# ENV IDM_DB_PORT "3306"

# ENV IDM_EX_AUTH_ENABLED false
# ENV IDM_EX_AUTH_ID_PREFIX "external_"
# ENV IDM_EX_AUTH_PASSWORD_ENCRYPTION "sha1"
# ENV IDM_EX_AUTH_PASSWORD_ENCRYPTION_KEY undefined
# ENV IDM_EX_AUTH_DB_HOST "localhost"
# ENV IDM_EX_AUTH_PORT undefined
# ENV IDM_EX_AUTH_DB_NAME "db_name"
# ENV IDM_EX_AUTH_DB_USER "db_user"
# ENV IDM_EX_AUTH_DB_PASS "db_pass"
# ENV IDM_EX_AUTH_DB_USER_TABLE "user_view"
# ENV IDM_EX_AUTH_DIALECT "mysql"

# ENV IDM_EMAIL_HOST "localhost"
# ENV IDM_EMAIL_PORT "25"
# ENV IDM_EMAIL_ADDRESS "noreply@localhost"
# ENV IDM_EMAIL_LIST null

# ENV IDM_TITLE "Identity Manager"
# ENV IDM_THEME "default"

# ENV IDM_EIDAS_ENABLED false
# ENV IDM_EIDAS_GATEWAY_HOST "localhost"
# ENV IDM_EIDAS_NODE_HOST "https://se-eidas.redsara.es/EidasNode/ServiceProvider"
# ENV IDM_EIDAS_METADATA_LIFETIME "31536000"

# ENV IDM_ADMIN_ID    "admin"
# ENV IDM_ADMIN_USER  "admin"
# ENV IDM_ADMIN_EMAIL "admin@test.com"
# ENV IDM_ADMIN_PASS  "1234"

           
