apiVersion: v1
kind: Service
metadata:
  name: idm-svc
  labels: 
    app: idm
spec:
  type: LoadBalancer
  ports:
  - name: normal
    port: 3000
    targetPort: 3000
  - name: ssl
    port: 443
    targetPort: 443
  selector:
    app: idm
---

 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: idm
   labels:
     app: idm
 spec:
   replicas: 1
   selector:
    matchLabels:
      app: idm
   template:
     metadata:
       labels:
         app: idm
     spec:
       containers:
       - name: fiware-idm
         image: fiware/idm
         ports:
         - containerPort: 3000
         - containerPort: 443
         env:
         - name: DATABASE_HOST
           value: wordpress-mysql
         - name: WORDPRESS_DB_PASSWORD
           valueFrom:
            secretKeyRef:
             name: mysql-pass
             key: password

