apiVersion: v1
kind: Service
metadata:
  name: cygnus
  labels: 
    app: cygnus
spec:
  #type: LoadBalancer
  ports:
  - #name: normal
    port: 5050
  selector:
    app: cygnus
---

 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: cygnus
   labels:
     app: cygnus
 spec:
   replicas: 1
   selector:
    matchLabels:
      app: cygnus
   template:
     metadata:
       labels:
         app: cygnus
     spec:
       containers:
       - name: cygnus
         image: fiware/cygnus-ngsi
         ports:
         - containerPort: 5050
         env:
         - name: CYGNUS_MYSQL_USER
           value: root
         - name: CYGNUS_MYSQL_PASS
           value: mysql
