apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\temp\k8s\kompose.exe --file fiware-idm.yaml convert
    kompose.version: 1.12.0 (0ab07be)
  creationTimestamp: null
  labels:
    io.kompose.service: fiware-idm
  name: fiware-idm
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  - name: "443"
    port: 443
    targetPort: 443
  selector:
    io.kompose.service: fiware-idm
status:
  loadBalancer: {}
