apiVersion: v1
kind: Service
metadata:
  name: idm-svc
  labels: 
    app: idm
spec:
  type: NodePort
  ports:
  - name: normal
    port: 3000
    targetPort: 3000
  - name: ssl
    port: 443
    targetPort: 443
  selector:
    app: idm

