apiVersion: apps/v1
kind: StatefulSet
metadata: 
   name: idm
spec: 
   serviceName: "idm-svc"
   replicas: 2
   selector:
     matchLabels: 
       app: idm   
   template:
     metadata:
       labels:
          app: idm    
     spec:
       containers:
       - name: mysql
         image: mysql/mysql-server:5.7.21
         ports:
         - containerPort: 3306
           name: mysql
         volumeMounts:
         - mountPath: /var/lib/mysql
           name: mysql-storage
         env:
         - name: MYSQL_ROOT_PASSWORD
           value: idm
       volumes:
       - name: mysql-storage
         persistentVolumeClaim:
           claimName: mysql-pvc
