apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    name: mongo 
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: mongo 
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongod 
spec:
  serviceName: mongodb-service 
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo 
        environment: test 
        replicaset: MainRepSet 
    spec:
      #terminationGracePeriodSeconds: 10
      volumes:
        - name: secrets-volume
          secret:
            secretName: shared-bootstrap-data
            defaultMode: 256
      containers:
        - name: mongod-container
          image: letavia/mongo:4.0.2_repset
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: password
          command: [ "/bin/sh", "-c"]
          args:
           - mongod --bind_ip 0.0.0.0 --replSet MainRepSet --auth --clusterAuthMode keyFile --keyFile /etc/secrets-volume/internal-auth-mongodb-keyfile --setParameter authenticationMechanisms=SCRAM-SHA-1; 
           #echo completed;
           #mongo --eval 'rs.initiate({_id: "MainRepSet", version: 1, members: [{ _id: 0, host : "mongod -0.mongodb-service .kubetest.svc.cluster.local:27017" },{ _id: 1, host : "mongod -1.mongodb-service .kubetest.svc.cluster.local:27017" },{ _id: 2, host : "mongod -2.mongodb-service .kubetest.svc.cluster.local:27017" }]})';
           #chmod 750 /usr/local/bin/mongodb_config_repset.sh;./usr/local/bin/mongodb_config_repset.sh;
            
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: secrets-volume
              readOnly: true
              mountPath: /etc/secrets-volume
            - name: mongodb-rs 
              mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb-rs 
      labels:
        replicaset: MainRepSet
      annotations:
        volume.beta.kubernetes.io/storage-class: "glusterfs-sc"
    spec:
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 1Gi