apiVersion: v1
kind: Service
metadata:
  name: mongodb-deploy
  labels:
    app: orion
    tier: mongodb
spec:
  ports:
    - port: 27017
  selector:
    app: orion
    tier: mongodb
  clusterIP: None
---

apiVersion: apps/v1 #for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mongodb-deploy
  labels:
    app: orion
    tier: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orion
      tier: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: orion
        tier: mongodb
    spec:
      containers:
      - image: mongo:4.0
        name: mongodb-deploy
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: admin
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db
        args: ["--auth"]
        #command: ["mongod","--setParameter","authenticationMechanisms=SCRAM-SHA-1"]  
        #args: ["--nojournal"]
      volumes:
      - name: mongodb-persistent-storage
        emptyDir: {}

