apiVersion: v1
kind: Service
metadata:
  name: mongodb-rs
  labels:
    app: orion
    tier: mongodb
spec:
  #type: LoadBalancer
  ports:
    - port: 27017
  selector:
    app: orion
    tier: mongodb
  clusterIP: None
---

apiVersion: apps/v1 #for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: mongodb-rs
  labels:
    app: orion
    tier: mongodb
spec:
  serviceName: "mongodb-rs"
  replicas: 3
  updateStrategy:  #default
    type: RollingUpdate
  selector:
    matchLabels:
      app: orion
      tier: mongodb
  template:
    metadata:
      labels:
        app: orion
        tier: mongodb
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongodb-rs
        image: mongo:4.0
        command:
        - mongod
        - "--replSet"
        - rs0
        - "--smallfiles"
        - "--noprealloc"
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: pvc
          mountPath: /data/db
      - name: mongo-sidecar
        image: cvallance/mongo-k8s-sidecar
        env:
        - name: MONGO\_SIDECAR\_POD\_LABELS
          value: "role=mongo,environment=test"
  volumeClaimTemplates:
  - metadata:
      name: pvc
    spec:
      accessModes: ["ReadWriteMany"]
      storageClassName: glusterfs-sc
      resources:
        requests:
          storage: 1Gi