apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  labels:
    app: orion
    db: mongodb
spec:
  storageClassName: glusterfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi