apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: fiware-idm
    db: mysql-57   
spec:
  #type: NodePort
  ports:
    - port: 3306
      #targetPort: 3306
      name: mysql-port
  selector: # label of target pods for service or rc 
    db: mysql-57  

#status:
  #loadBalancer: {}

