apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: mysql
spec:
  storageClassName: glusterfs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  #volumeName: pvc-f686cdda-89c4-11e8-8dae-42010a800034