apiVersion: v1
kind: Service
metadata:
  name: mysql57
  labels:
    app: idm
spec:
  ports:
    - port: 3306
  selector:
    app: idm
    tier: mysql
  clusterIP: None
---

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql57
  labels:
    app: idm
spec:
  selector:
    matchLabels:
      app: idm
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: idm
        tier: mysql
    spec:
      containers:
      - image: mysql/mysql-server:5.7.21
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: MYSQL_ROOT_HOST
          value: wordpress
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql57-pvc
