apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: idm
    tier: mysql
spec:
  ports:
    - port: 3306
  selector:
    tier: mysql
  #type: LoadBalancer
---

apiVersion: apps/v1 #for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
  labels:
    app: idm
    tier: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idm
      tier: mysql
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: idm
        tier: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: test

$ docker run -d --name elasticsearch --net somenetwork -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" elasticsearch:tag
