apiVersion: v1
kind: PersistentVolume
metadata:
  name: stateful-vol
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: glusterfs-sc