kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wirecloud-pvc
  namespace: kubecity
  #annotations:
   #  volume.beta.kubernetes.io/storage-class: "test"
spec:
  #mountOptions: 
  storageClassName: glusterfs-sc
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi