apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rs
  labels:
    type: myapp-rs-label
spec:
  replicas: 1
  selector:
      type: myapp
  template:
    metadata:
      labels:
        type: myapp
    spec:   
      containers:
      - name: frontend
        image: salrashid123/single_node_filer
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /_ah/health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
        env:
        - name: CUR_TYPE
          value: metadata.labels.type
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - mountPath: "/apps/data"
          name: mypd
      volumes:
      - name: mypd
        nfs:
          path: "/data"
          server: 10.128.0.6