kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kubecity-admin-rb-cluster
  namespace: kubecity
subjects:
- kind: ServiceAccount
  name: kubecity-sa
  namespace: kubecity
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin