kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kubetest-user-full-access
  namespace: kubetest
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
  