kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kubetest-iam
  namespace: kubetest
subjects:
- kind: ServiceAccount
  name: turis-kubetest-sa
  namespace: kubetest
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubetest-user-full-access