kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nfs
  labels:
    app: myapp
    #kubernetes.io/cluster-service: "true"
  #annotations:
    #storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/nfs
parameters:
  #type: io1
  #iopsPerGB: '30'
    path: "/"
    server: 10.39.243.19
#nfs-server.default.svc.cluster.local