apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.13.0 (84fa826)
  creationTimestamp: null
  labels:
    io.kompose.service: fiware-idm
  name: fiware-idm
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: fiware-idm
    spec:
      containers:
      - env:
        - name: DATABASE_HOST
          value: mysql
        image: fiware/idm
        name: fiware-idm
        ports:
        - containerPort: 3000
        - containerPort: 443
        resources: {}
      restartPolicy: Always
status: {}
