apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wilma.fullname" . }}
  labels:
    app: {{ include "wilma.name" . }}
    chart: {{ include "wilma.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}
type: Opaque
data:
  magicKey: kamvret