apiVersion: v1
kind: Service
metadata:
  name: {{ include "keyrock.fullname" . }}
  labels:
    app: {{ include "keyrock.name" . }}
    chart: {{ include "keyrock.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }}    
spec:
  type: {{ .Values.service.type }}
  ports: 
  - name: {{ .Values.service.ports.idmHttp.name }}
    port: {{ .Values.service.ports.idmHttp.port }}
    targetPort: {{ .Values.service.ports.idmHttp.targetPort }}
  - name: {{ .Values.service.ports.idmHttps.name }}
    port: {{ .Values.service.ports.idmHttps.port }}
    targetPort: {{ .Values.service.ports.idmHttps.targetPort }}
  selector:
    app: {{ include "keyrock.name" . }}
    release: {{ .Release.Name }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | indent 4 }}
{{- end }} 